// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // Auto-generate sidebar from the docs/ folder structure
  wikiSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
